#ifndef QSINGLEAPPGUARD_GLOBAL_H
#define QSINGLEAPPGUARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QSINGLEAPPGUARD_LIBRARY)
#  define QSINGLEAPPGUARD_EXPORT Q_DECL_EXPORT
#else
#  define QSINGLEAPPGUARD_EXPORT Q_DECL_IMPORT
#endif

#endif // QSINGLEAPPGUARD_GLOBAL_H
